FROM python:3.8
MAINTAINER Fieldea
ENV PYTHONUNBUFFERED=1
ADD . /usr/src/app
WORKDIR /usr/src/app
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
RUN rm -rf /usr/src/app
COPY . /usr/src/app
EXPOSE 8080
CMD ["/bin/sh", "./docker-entrypoint.sh"]