# Generated by Django 3.0.4 on 2020-05-27 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location', models.CharField(max_length=200)),
                ('StartID', models.IntegerField(default=0)),
                ('EndID', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Diagram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.IntegerField(default=0)),
                ('Title', models.CharField(max_length=255)),
                ('Description', models.CharField(max_length=255)),
                ('UploadDate', models.DateTimeField()),
                ('Visit', models.IntegerField(default=0)),
                ('DataSourceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='climate.DataSource')),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.IntegerField(default=0)),
                ('Temp', models.FloatField(default=0.0)),
                ('Anomaly', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Keyword', models.CharField(max_length=255)),
                ('Order', models.IntegerField(default=0)),
                ('DisplayMode', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TagDiagram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DiagramID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='climate.Diagram')),
                ('TagID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='climate.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Visit', models.IntegerField(default=0)),
                ('MemberID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='climate.Member')),
            ],
        ),
        migrations.AddField(
            model_name='diagram',
            name='MemberID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='climate.Member'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PostDate', models.DateTimeField()),
                ('Content', models.CharField(max_length=255)),
                ('DiagramID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='climate.Diagram')),
            ],
        ),
    ]
